CREATE TABLE IF NOT EXISTS loan_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mobile VARCHAR(15) NOT NULL,
    pan VARCHAR(10),
    pan_name VARCHAR(255),
    dob VARCHAR(20),
    gender VARCHAR(10),
    credit_score INT,
    credit_report JSON,
    vehicle_rc VARCHAR(20),
    vehicle_model VARCHAR(255),
    vehicle_year INT,
    vehicle_make VARCHAR(255),
    owner_name VARCHAR(255),
    fuel_type VARCHAR(50),
    vehicle_color VARCHAR(50),
    income INT,
    employment VARCHAR(100),
    application_status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);